@extends('layouts.app')

@section('title', $exercise->name.' History')

@push('styles')
<style>
    .eh-shell{padding:22px 24px 48px;background:#f7f9fc;min-height:100vh}.eh-wrap{max-width:950px;margin:auto}.eh-head{display:flex;align-items:flex-start;gap:12px;margin-bottom:15px}.eh-main{flex:1}.eh-back{font-size:12px;color:#64748b;text-decoration:none}.eh-title{font-size:22px;font-weight:800;color:#0f172a;margin:9px 0 3px}.eh-sub{font-size:12px;color:#64748b}.eh-btn{display:inline-flex;align-items:center;gap:6px;border:1px solid #dbe3ee;border-radius:9px;padding:8px 12px;font-size:12px;font-weight:700;text-decoration:none;color:#475569;background:#fff}.eh-btn:hover{color:#4338ca;border-color:#a5b4fc;background:#f8faff}.eh-stats{display:grid;grid-template-columns:repeat(5,1fr);gap:9px;margin-bottom:14px}.eh-stat,.eh-card{background:#fff;border:1px solid #e2e8f0;border-radius:12px}.eh-stat{padding:13px}.eh-val{font-size:19px;font-weight:850;color:#1e293b}.eh-lbl{font-size:10px;color:#64748b;text-transform:uppercase;font-weight:800;margin-top:4px}.eh-card{overflow:hidden}.eh-card-head{padding:12px 15px;border-bottom:1px solid #eef2f7;font-size:13px;font-weight:800;color:#1e293b}.eh-table{width:100%;border-collapse:collapse}.eh-table th,.eh-table td{padding:10px 15px;border-bottom:1px solid #f1f5f9;text-align:left;font-size:12px}.eh-table th{font-size:10px;text-transform:uppercase;color:#64748b}.eh-table tr:last-child td{border-bottom:0}.eh-muted{font-size:11px;color:#64748b}.eh-empty{text-align:center;padding:45px;color:#64748b}@media(max-width:650px){.eh-shell{padding:14px 12px 40px}.eh-title{font-size:19px}.eh-head .eh-btn span{display:none}.eh-stats{grid-template-columns:repeat(2,1fr)}.eh-table th:nth-child(4),.eh-table td:nth-child(4){display:none}}
</style>
@endpush

@section('content')
<div class="eh-shell"><div class="eh-wrap"><div class="eh-head"><div class="eh-main"><a class="eh-back" href="{{ route('workouts.exercises.index') }}"><i class="bi bi-arrow-left"></i> Exercise library</a><div class="eh-title">{{ $exercise->name }}</div><div class="eh-sub">Performance history across every workout plan and cycle</div></div><a class="eh-btn" href="{{ route('workouts.reports.index') }}"><i class="bi bi-bar-chart"></i><span>Reports</span></a></div>
    <div class="eh-stats"><div class="eh-stat"><div class="eh-val">{{ $stats['sessions'] }}</div><div class="eh-lbl">Sessions</div></div><div class="eh-stat"><div class="eh-val">{{ $stats['sets'] }}</div><div class="eh-lbl">Sets</div></div><div class="eh-stat"><div class="eh-val">{{ $stats['reps'] }}</div><div class="eh-lbl">Total reps</div></div><div class="eh-stat"><div class="eh-val">{{ $stats['volume'] }}</div><div class="eh-lbl">Volume</div></div><div class="eh-stat"><div class="eh-val">{{ $stats['best_weight'] ?? '—' }}</div><div class="eh-lbl">Best weight</div></div></div>
    <div class="eh-card"><div class="eh-card-head">Session history</div>@if($sessions->count())<table class="eh-table"><thead><tr><th>Date</th><th>Sets</th><th>Reps</th><th>Volume</th><th>Max weight</th><th>Avg RIR</th></tr></thead><tbody>@foreach($sessions as $session)<tr><td><strong>{{ \Carbon\Carbon::parse($session['date'])->format('M j, Y') }}</strong></td><td>{{ $session['sets'] }}</td><td>{{ $session['reps'] }}</td><td>{{ $session['volume'] }}</td><td>{{ $session['max_weight'] ?: '—' }}</td><td>{{ $session['avg_rir'] ?? '—' }}</td></tr>@endforeach</tbody></table>@else<div class="eh-empty"><i class="bi bi-graph-up fs-3"></i><p class="mb-0">No completed sets for this exercise yet.</p></div>@endif</div>
</div></div>
@endsection
