@extends('layouts.app')

@section('title', 'Review Workout Import')

@push('styles')
<style>
    .ip-shell{padding:22px 24px 48px;background:#f7f9fc;min-height:100vh}.ip-wrap{max-width:1100px;margin:auto}.ip-head{display:flex;align-items:flex-start;gap:12px;margin-bottom:15px}.ip-main{flex:1}.ip-back{font-size:12px;color:#64748b;text-decoration:none}.ip-title{font-size:22px;font-weight:800;color:#0f172a;margin:9px 0 3px}.ip-sub{font-size:12px;color:#64748b}.ip-btn{display:inline-flex;align-items:center;gap:6px;border:1px solid #dbe3ee;border-radius:9px;padding:8px 13px;font-size:12px;font-weight:800;text-decoration:none;color:#475569;background:#fff}.ip-btn.primary{background:#4f46e5;border-color:#4f46e5;color:#fff}.ip-card{background:#fff;border:1px solid #e2e8f0;border-radius:14px;overflow:hidden;margin-bottom:10px}.ip-card-head{padding:12px 15px;background:#fafbfc;border-bottom:1px solid #eef2f7;display:flex;align-items:center;gap:8px}.ip-day-title{font-size:14px;font-weight:800;color:#1e293b;flex:1}.ip-pill{font-size:10px;font-weight:800;border-radius:20px;padding:4px 8px;background:#eef2ff;color:#4338ca}.ip-pill.rest{background:#f1f5f9;color:#64748b}.ip-pill.recovery{background:#ecfeff;color:#0e7490}.ip-card-body{padding:10px 15px}.ip-ex{display:grid;grid-template-columns:1fr 160px 90px;gap:10px;align-items:center;padding:8px 0;border-bottom:1px solid #f1f5f9;font-size:12px}.ip-ex:last-child{border-bottom:0}.ip-ex-name{font-weight:800;color:#334155}.ip-ex-target{font-size:11px;color:#64748b}.ip-match{font-size:10px;font-weight:800;color:#15803d;background:#dcfce7;border-radius:20px;padding:4px 7px;text-align:center}.ip-match.new{color:#b45309;background:#fef3c7}.ip-rules{padding:12px 15px}.ip-rules li{font-size:12px;color:#475569;margin-bottom:5px}.ip-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}@media(max-width:650px){.ip-shell{padding:14px 12px 40px}.ip-title{font-size:19px}.ip-head .ip-btn span{display:none}.ip-ex{grid-template-columns:1fr 85px}.ip-ex-target{grid-column:1/-1;grid-row:2}.ip-card-body{padding:8px 11px}}
</style>
@endpush

@section('content')
<div class="ip-shell"><div class="ip-wrap"><div class="ip-head"><div class="ip-main"><a class="ip-back" href="{{ route('workouts.plans.index') }}"><i class="bi bi-arrow-left"></i> Workout plans</a><div class="ip-title">Review: {{ $import->structure['title'] ?? 'Imported workout' }}</div><div class="ip-sub">Matched movements will reuse your library. New movements will be created once after confirmation.@if(!empty($import->structure['week_number'])) Week {{ $import->structure['week_number'] }}.@endif @if(!empty($import->structure['start_date'])) Starts {{ \Carbon\Carbon::parse($import->structure['start_date'])->format('D, M j, Y') }} (DAY 1).@endif @if(!empty($import->structure['goal'])) Goal: {{ $import->structure['goal'] }}.@endif</div></div><a class="ip-btn" href="{{ route('workouts.imports.create') }}"><i class="bi bi-arrow-repeat"></i><span>Start over</span></a></div>
    @foreach($days as $day)<section class="ip-card"><div class="ip-card-head"><div class="ip-day-title">{{ ucfirst($day['weekday']) }} · {{ $day['title'] }}</div><span class="ip-pill {{ $day['type'] }}">{{ ucfirst($day['type']) }}</span></div><div class="ip-card-body">@forelse($day['exercises'] as $exercise)<div class="ip-ex"><div><div class="ip-ex-name">{{ $exercise['name'] }}</div><div class="ip-ex-target">{{ $exercise['section'] }} · {{ $exercise['is_circuit'] ? 'Circuit × '.($exercise['circuit_rounds'] ?: $exercise['target_sets'] ?: 1) : ($exercise['is_amrap'] ? 'AMRAP' : (($exercise['target_sets'] ?: 1).' × '.($exercise['rep_min'] ?: '—').'–'.($exercise['rep_max'] ?: '—'))) }}</div></div><div class="ip-ex-target">{{ $exercise['notes'] }}</div><span class="ip-match {{ $exercise['match_status'] === 'new' ? 'new' : '' }}">{{ $exercise['match_status'] === 'matched' ? 'Matched: '.$exercise['matched_exercise_name'] : 'New movement' }}</span></div>@empty<span class="text-secondary small">No movements planned.</span>@endforelse</div></section>@endforeach
    @if(count($import->structure['rules'] ?? []))<section class="ip-card"><div class="ip-card-head"><div class="ip-day-title">Rules</div></div><ul class="ip-rules mb-0">@foreach($import->structure['rules'] as $rule)<li>{{ $rule }}</li>@endforeach</ul></section>@endif
    <div class="ip-actions"><form method="POST" action="{{ route('workouts.imports.confirm', $import) }}">@csrf<button class="ip-btn primary" type="submit"><i class="bi bi-check2-circle"></i> Confirm and create plan</button></form></div>
</div></div>
@endsection
